import 'package:smart_select/smart_select.dart';

// class LanguagesList {
//   static List<S2Choice<String>> languages = [
//     S2Choice<String>(value: 'af', title: 'Afrikaans'),
//     S2Choice<String>(value: 'sq', title: 'Albanian'),
//     S2Choice<String>(value: 'am', title: 'Amharic'),
//     S2Choice<String>(value: 'ar', title: 'Arabic'),
//     S2Choice<String>(value: 'hy', title: 'Armenian'),
//     S2Choice<String>(value: 'az', title: 'Azerbaijani'),
//     S2Choice<String>(value: 'eu', title: 'Basque'),
//     S2Choice<String>(value: 'be', title: 'Belarusian'),
//     S2Choice<String>(value: 'bn', title: 'Bengali'),
//     S2Choice<String>(value: 'bs', title: 'Bosnian'),
//     S2Choice<String>(value: 'bg', title: 'Bulgarian'),
//     S2Choice<String>(value: 'ca', title: 'Catalan'),
//     S2Choice<String>(value: 'ceb', title: 'Cebuano'),
//     S2Choice<String>(value: 'zh-cn', title: 'Chinese (Simplified)'),
//     S2Choice<String>(value: 'zh-tw', title: 'Chinese (Traditional)'),
//     S2Choice<String>(value: 'co', title: 'Corsican'),
//     S2Choice<String>(value: 'hr', title: 'Croatian'),
//     S2Choice<String>(value: 'cs', title: 'Czech'),
//     S2Choice<String>(value: 'da', title: 'Danish'),
//     S2Choice<String>(value: 'nl', title: 'Dutch'),
//     S2Choice<String>(value: 'en', title: 'English'),
//     S2Choice<String>(value: 'eo', title: 'Esperanto'),
//     S2Choice<String>(value: 'et', title: 'Estonian'),
//     S2Choice<String>(value: 'fi', title: 'Finnish'),
//     S2Choice<String>(value: 'fr', title: 'French'),
//     S2Choice<String>(value: 'fy', title: 'Frisian'),
//     S2Choice<String>(value: 'gl', title: 'Galician'),
//     S2Choice<String>(value: 'ka', title: 'Georgian'),
//     S2Choice<String>(value: 'de', title: 'German'),
//     S2Choice<String>(value: 'el', title: 'Greek'),
//     S2Choice<String>(value: 'gu', title: 'Gujarati'),
//     S2Choice<String>(value: 'ht', title: 'Haitian Creole'),
//     S2Choice<String>(value: 'ha', title: 'Hausa'),
//     S2Choice<String>(value: 'haw', title: 'Hawaiian'),
//     S2Choice<String>(value: 'he', title: 'Hebrew'),
//     S2Choice<String>(value: 'hi', title: 'Hindi'),
//     S2Choice<String>(value: 'hmn', title: 'Hmong'),
//     S2Choice<String>(value: 'hu', title: 'Hungarian'),
//     S2Choice<String>(value: 'is', title: 'Icelandic'),
//     S2Choice<String>(value: 'ig', title: 'Igbo'),
//     S2Choice<String>(value: 'id', title: 'Indonesian'),
//     S2Choice<String>(value: 'ga', title: 'Irish'),
//     S2Choice<String>(value: 'it', title: 'Italian'),
//     S2Choice<String>(value: 'ja', title: 'Japanese'),
//     S2Choice<String>(value: 'jv', title: 'Javanese'),
//     S2Choice<String>(value: 'kn', title: 'Kannada'),
//     S2Choice<String>(value: 'kk', title: 'Kazakh'),
//     S2Choice<String>(value: 'km', title: 'Khmer'),
//     S2Choice<String>(value: 'rw', title: 'Kinyarwanda'),
//     S2Choice<String>(value: 'ko', title: 'Korean'),
//     S2Choice<String>(value: 'ku', title: 'Kurdish'),
//     S2Choice<String>(value: 'ky', title: 'Kyrgyz'),
//     S2Choice<String>(value: 'lo', title: 'Lao'),
//     S2Choice<String>(value: 'la', title: 'Latin'),
//     S2Choice<String>(value: 'lv', title: 'Latvian'),
//     S2Choice<String>(value: 'lt', title: 'Lithuanian'),
//     S2Choice<String>(value: 'lb', title: 'Luxembourgish'),
//     S2Choice<String>(value: 'mk', title: 'Macedonian'),
//     S2Choice<String>(value: 'mg', title: 'Malagasy'),
//     S2Choice<String>(value: 'ms', title: 'Malay'),
//     S2Choice<String>(value: 'ml', title: 'Malayalam'),
//     S2Choice<String>(value: 'mt', title: 'Maltese'),
//     S2Choice<String>(value: 'mi', title: 'Maori'),
//     S2Choice<String>(value: 'mr', title: 'Marathi'),
//     S2Choice<String>(value: 'mn', title: 'Mongolian'),
//     S2Choice<String>(value: 'my', title: 'Myanmar (Burmese)'),
//     S2Choice<String>(value: 'ne', title: 'Nepali'),
//     S2Choice<String>(value: 'no', title: 'Norwegian'),
//     S2Choice<String>(value: 'ny', title: 'Nyanja (Chichewa)'),
//     S2Choice<String>(value: 'or', title: 'Odia (Oriya)'),
//     S2Choice<String>(value: 'ps', title: 'Pashto'),
//     S2Choice<String>(value: 'fa', title: 'Persian'),
//     S2Choice<String>(value: 'pl', title: 'Polish'),
//     S2Choice<String>(value: 'pt', title: 'Portuguese (Portugal, Brazil)'),
//     S2Choice<String>(value: 'pa', title: 'Punjabi'),
//     S2Choice<String>(value: 'ro', title: 'Romanian'),
//     S2Choice<String>(value: 'ru', title: 'Russian'),
//     S2Choice<String>(value: 'sm', title: 'Samoan'),
//     S2Choice<String>(value: 'gd', title: 'Scots Gaelic'),
//     S2Choice<String>(value: 'sr', title: 'Serbian'),
//     S2Choice<String>(value: 'st', title: 'Sesotho'),
//     S2Choice<String>(value: 'sn', title: 'Shona'),
//     S2Choice<String>(value: 'sd', title: 'Sindhi'),
//     S2Choice<String>(value: 'si', title: 'Sinhala (Sinhalese)'),
//     S2Choice<String>(value: 'sk', title: 'Slovak'),
//     S2Choice<String>(value: 'sl', title: 'Slovenian'),
//     S2Choice<String>(value: 'so', title: 'Somali'),
//     S2Choice<String>(value: 'es', title: 'Spanish'),
//     S2Choice<String>(value: 'su', title: 'Sundanese'),
//     S2Choice<String>(value: 'sw', title: 'Swahili'),
//     S2Choice<String>(value: 'sv', title: 'Swedish'),
//     S2Choice<String>(value: 'tl', title: 'Tagalog (Filipino)'),
//     S2Choice<String>(value: 'tg', title: 'Tajik'),
//     S2Choice<String>(value: 'ta', title: 'Tamil'),
//     S2Choice<String>(value: 'tt', title: 'Tatar'),
//     S2Choice<String>(value: 'te', title: 'Telugu'),
//     S2Choice<String>(value: 'th', title: 'Thai'),
//     S2Choice<String>(value: 'tr', title: 'Turkish'),
//     S2Choice<String>(value: 'tk', title: 'Turkmen'),
//     S2Choice<String>(value: 'uk', title: 'Ukrainian'),
//     S2Choice<String>(value: 'ur', title: 'Urdu'),
//     S2Choice<String>(value: 'ug', title: 'Uyghur'),
//     S2Choice<String>(value: 'uz', title: 'Uzbek'),
//     S2Choice<String>(value: 'vi', title: 'Vietnamese'),
//     S2Choice<String>(value: 'cy', title: 'Welsh'),
//     S2Choice<String>(value: 'xh', title: 'Xhosa'),
//     S2Choice<String>(value: 'yi', title: 'Yiddish'),
//     S2Choice<String>(value: 'yo', title: 'Yoruba'),
//     S2Choice<String>(value: 'zu', title: 'Zulu'),
//   ];

//   static List<S2Choice<String>> levels = [
//     S2Choice<String>(value: '1', title: 'Beginner'),
//     S2Choice<String>(value: '2', title: 'Elementary'),
//     S2Choice<String>(value: '3', title: 'Intermediate'),
//     S2Choice<String>(value: '4', title: 'Advanced'),
//     S2Choice<String>(value: '5', title: 'Proficient'),
//   ];
// }

// modified languages codes
class LanguagesList {
  static List<S2Choice<String>> languages = [
    S2Choice<String>(value: 'af', title: 'Afrikaans'),
    S2Choice<String>(value: 'sq', title: 'Albanian'),
    S2Choice<String>(value: 'am', title: 'Amharic'),
    S2Choice<String>(value: 'ar', title: 'Arabic'),
    S2Choice<String>(value: 'hy', title: 'Armenian'),
    S2Choice<String>(value: 'az', title: 'Azerbaijani'),
    S2Choice<String>(value: 'eu', title: 'Basque'),
    S2Choice<String>(value: 'be', title: 'Belarusian'),
    S2Choice<String>(value: 'bn', title: 'Bengali'),
    S2Choice<String>(value: 'bs', title: 'Bosnian'),
    S2Choice<String>(value: 'bg', title: 'Bulgarian'),
    S2Choice<String>(value: 'ca', title: 'Catalan'),
    S2Choice<String>(value: 'ceb', title: 'Cebuano'),
    S2Choice<String>(value: 'ny', title: 'Chichewa'),
    S2Choice<String>(value: 'zh-cn', title: 'Chinese Simplified'),
    S2Choice<String>(value: 'zh-tw', title: 'Chinese Traditional'),
    S2Choice<String>(value: 'co', title: 'Corsican'),
    S2Choice<String>(value: 'hr', title: 'Croatian'),
    S2Choice<String>(value: 'cs', title: 'Czech'),
    S2Choice<String>(value: 'da', title: 'Danish'),
    S2Choice<String>(value: 'nl', title: 'Dutch'),
    S2Choice<String>(value: 'en', title: 'English'),
    S2Choice<String>(value: 'eo', title: 'Esperanto'),
    S2Choice<String>(value: 'et', title: 'Estonian'),
    S2Choice<String>(value: 'tl', title: 'Filipino'),
    S2Choice<String>(value: 'fi', title: 'Finnish'),
    S2Choice<String>(value: 'fr', title: 'French'),
    S2Choice<String>(value: 'fy', title: 'Frisian'),
    S2Choice<String>(value: 'gl', title: 'Galician'),
    S2Choice<String>(value: 'ka', title: 'Georgian'),
    S2Choice<String>(value: 'de', title: 'German'),
    S2Choice<String>(value: 'el', title: 'Greek'),
    S2Choice<String>(value: 'gu', title: 'Gujarati'),
    S2Choice<String>(value: 'ht', title: 'Haitian Creole'),
    S2Choice<String>(value: 'ha', title: 'Hausa'),
    S2Choice<String>(value: 'haw', title: 'Hawaiian'),
    S2Choice<String>(value: 'iw', title: 'Hebrew'),
    S2Choice<String>(value: 'hi', title: 'Hindi'),
    S2Choice<String>(value: 'hmn', title: 'Hmong'),
    S2Choice<String>(value: 'hu', title: 'Hungarian'),
    S2Choice<String>(value: 'is', title: 'Icelandic'),
    S2Choice<String>(value: 'ig', title: 'Igbo'),
    S2Choice<String>(value: 'id', title: 'Indonesian'),
    S2Choice<String>(value: 'ga', title: 'Irish'),
    S2Choice<String>(value: 'it', title: 'Italian'),
    S2Choice<String>(value: 'ja', title: 'Japanese'),
    S2Choice<String>(value: 'jw', title: 'Javanese'),
    S2Choice<String>(value: 'kn', title: 'Kannada'),
    S2Choice<String>(value: 'kk', title: 'Kazakh'),
    S2Choice<String>(value: 'km', title: 'Khmer'),
    S2Choice<String>(value: 'ko', title: 'Korean'),
    S2Choice<String>(value: 'ku', title: 'Kurdish (Kurmanji)'),
    S2Choice<String>(value: 'ky', title: 'Kyrgyz'),
    S2Choice<String>(value: 'lo', title: 'Lao'),
    S2Choice<String>(value: 'la', title: 'Latin'),
    S2Choice<String>(value: 'lv', title: 'Latvian'),
    S2Choice<String>(value: 'lt', title: 'Lithuanian'),
    S2Choice<String>(value: 'lb', title: 'Luxembourgish'),
    S2Choice<String>(value: 'mk', title: 'Macedonian'),
    S2Choice<String>(value: 'mg', title: 'Malagasy'),
    S2Choice<String>(value: 'ms', title: 'Malay'),
    S2Choice<String>(value: 'ml', title: 'Malayalam'),
    S2Choice<String>(value: 'mt', title: 'Maltese'),
    S2Choice<String>(value: 'mi', title: 'Maori'),
    S2Choice<String>(value: 'mr', title: 'Marathi'),
    S2Choice<String>(value: 'mn', title: 'Mongolian'),
    S2Choice<String>(value: 'my', title: 'Myanmar (Burmese)'),
    S2Choice<String>(value: 'ne', title: 'Nepali'),
    S2Choice<String>(value: 'no', title: 'Norwegian'),
    S2Choice<String>(value: 'ps', title: 'Pashto'),
    S2Choice<String>(value: 'fa', title: 'Persian'),
    S2Choice<String>(value: 'pl', title: 'Polish'),
    S2Choice<String>(value: 'pt', title: 'Portuguese'),
    S2Choice<String>(value: 'pa', title: 'Punjabi'),
    S2Choice<String>(value: 'ro', title: 'Romanian'),
    S2Choice<String>(value: 'ru', title: 'Russian'),
    S2Choice<String>(value: 'sm', title: 'Samoan'),
    S2Choice<String>(value: 'gd', title: 'Scots Gaelic'),
    S2Choice<String>(value: 'sr', title: 'Serbian'),
    S2Choice<String>(value: 'st', title: 'Sesotho'),
    S2Choice<String>(value: 'sn', title: 'Shona'),
    S2Choice<String>(value: 'sd', title: 'Sindhi'),
    S2Choice<String>(value: 'si', title: 'Sinhala'),
    S2Choice<String>(value: 'sk', title: 'Slovak'),
    S2Choice<String>(value: 'sl', title: 'Slovenian'),
    S2Choice<String>(value: 'so', title: 'Somali'),
    S2Choice<String>(value: 'es', title: 'Spanish'),
    S2Choice<String>(value: 'su', title: 'Sundanese'),
    S2Choice<String>(value: 'sw', title: 'Swahili'),
    S2Choice<String>(value: 'sv', title: 'Swedish'),
    S2Choice<String>(value: 'tg', title: 'Tajik'),
    S2Choice<String>(value: 'ta', title: 'Tamil'),
    S2Choice<String>(value: 'te', title: 'Telugu'),
    S2Choice<String>(value: 'th', title: 'Thai'),
    S2Choice<String>(value: 'tr', title: 'Turkish'),
    S2Choice<String>(value: 'uk', title: 'Ukrainian'),
    S2Choice<String>(value: 'ur', title: 'Urdu'),
    S2Choice<String>(value: 'uz', title: 'Uzbek'),
    S2Choice<String>(value: 'ug', title: 'Uyghur'),
    S2Choice<String>(value: 'vi', title: 'Vietnamese'),
    S2Choice<String>(value: 'cy', title: 'Welsh'),
    S2Choice<String>(value: 'xh', title: 'Xhosa'),
    S2Choice<String>(value: 'yi', title: 'Yiddish'),
    S2Choice<String>(value: 'yo', title: 'Yoruba'),
    S2Choice<String>(value: 'zu', title: 'Zulu')
  ];
  static List<S2Choice<String>> levels = [
    S2Choice<String>(value: '1', title: 'Beginner'),
    S2Choice<String>(value: '2', title: 'Elementary'),
    S2Choice<String>(value: '3', title: 'Intermediate'),
    S2Choice<String>(value: '4', title: 'Advanced'),
    S2Choice<String>(value: '5', title: 'Proficient'),
  ];

  static List<Map<String, String>> languageLevels = [
    {'value': '1', 'title': 'Beginner'},
    {'value': '2', 'title': 'Elementary'},
    {'value': '3', 'title': 'Intermediate'},
    {'value': '4', 'title': 'Advanced'},
    {'value': '5', 'title': 'Proficient'},
  ];
}
